### ISSUE TITLE
todomvc example panics

### ISSUE THREAD

**Issue by pwaller** [albrow/temple-example#5]
I did:

```
~/.local/src/github.com/go-humble/examples$ go generate -v ./...
```

And then tried to run the app:

```
~/.local/src/github.com/go-humble/examples/todomvc/go$ go run main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4b1308]

goroutine 1 [running]:
panic(0x92d6c0, 0xc82000a160)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/gopherjs/gopherjs/js.(*Object).Get(0x0, 0xa722f0, 0xc, 0x6347db)
    /home/pwaller/.local/src/github.com/gopherjs/gopherjs/js/js.go:32 +0x18
github.com/go-humble/locstor.init()
    /home/pwaller/.local/src/github.com/go-humble/locstor/local_storage.go:14 +0x80
github.com/go-humble/examples/todomvc/go/models.init()
    /home/pwaller/.local/src/github.com/go-humble/examples/todomvc/go/models/todo_list.go:81 +0x51
main.init()
    /home/pwaller/.local/src/github.com/go-humble/examples/todomvc/go/main.go:69 +0x45
exit status 2
```

**Comment by albrow** [comment]
@pwaller The [README for the TodoMVC example](https://github.com/go-humble/examples/tree/master/todomvc) explains how to start the app in detail. You cannot run **go/main.go** directly as that is a file that gets compiled into JavaScript. Instead, to start the app you should run `go run serve.go`.

Give that a try and let me know whether it works.

**Comment by pwaller** [comment]
That was it, thanks.
